## To modify by developer(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'rigol'  #to be modified, for instance daqmx then rename
package-url = 'https://github.com/nano713/pymodaq_plugins_rigol' #to modify
description = 'Set of PyMoDAQ plugins for instruments from RIGOL including DSA815 spectrum analyzer.'

author = 'Author Name'
author-email = 'Author email'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pymodaq>=4.3.6', 'pyvisa']

[features]  # defines the plugin features contained into this plugin
instruments = true  # true if plugin contains instrument classes (else false, notice the lowercase for toml files)
extensions = false  # true if plugins contains dashboard extensions
models = false  # true if plugins contains pid models or other models (optimisation...)
h5exporters = false  # true if plugin contains custom h5 file exporters
scanners = false  # true if plugin contains custom scan layout (daq_scan extensions)

